spring.datasource.url=jdbc:sqlserver://localhost;databaseName=RegistroPonto;integratedSecurity=true;encrypt=true;trustServerCertificate=true;
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver


spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
server.port=8080

# JWT
jwt.secret=cmVnaXN0cm9kZXBvbnRvYXBwc2VjcmV0a2V5andiYXNlNjRlbmNvZGVkMjAyNg==
jwt.expiration=86400000
